[package]
name = "benchmark_server"
version = "0.0.0"
edition = "2021"

[dependencies]
async-graphql = "6.0.11"
async-graphql-actix-web = "7.0.0"
actix-web = { version = "4.4.1", default-features = false, features = [
  "macros",
] }
