[package]
name = "conductor-cf-worker"
version = "0.1.0"
edition = "2021"
description = "Conductor Cloudflare Worker runtime"
license = "MIT"
repository = "https://github.com/the-guild-org/conductor"

# https://github.com/rustwasm/wasm-pack/issues/1247
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { git = "https://github.com/dotansimha/workers-rs.git", rev = "6de1efc2ef155236d8caf376cce2a0f9972e241f" }
conductor_config = { path = "../../libs/config" }
conductor_engine = { path = "../../libs/engine" }
conductor_common = { path = "../../libs/common" }
conductor_logger = { path = "../../libs/logger" }
tracing = { workspace = true }
tracing-web = "0.1.3"
tracing-subscriber = { workspace = true, features = ['time', 'json'] }
time = { version = "0.3.34", features = ['wasm-bindgen'] }
console_error_panic_hook = "0.1.7"
