[package]
name = "conductor-cf-worker"
version = "0.1.0"
edition = "2021"
description = "Conductor Cloudflare Worker runtime"
license = "MIT"
repository = "https://github.com/the-guild-org/conductor-t2"

# https://github.com/rustwasm/wasm-pack/issues/1247
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = "0.0.18"
conductor_config = { path = "../../libs/config" }
conductor_engine = { path = "../../libs/engine" }
conductor_common = { path = "../../libs/common" }
tracing-web = "0.1.3"
tracing-subscriber = { version = "0.3.18", features = ['time', 'json'] }
time = { version = "0.3.31", features = ['wasm-bindgen'] }
console_error_panic_hook = "0.1.7"
