[package]
name = "conductor"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "conductor"
path = "src/main.rs"

[lib]
name = "conductor"
path = "src/lib.rs"

[dependencies]
tokio = { workspace = true, features = ["full"] }
conductor_config = { path = "../../libs/config" }
conductor_engine = { path = "../../libs/engine" }
conductor_common = { path = "../../libs/common" }
conductor_tracing = { path = "../../libs/tracing" }
conductor_logger = { path = "../../libs/logger" }
anyhow = { workspace = true }
actix-web = "4.9.0"
futures-util = "0.3.31"
ulid = "1.1.3"
tracing = { workspace = true }
openssl = { version = "0.10.68", features = ["vendored"] }
tracing-subscriber = { workspace = true, features = [
  "registry",
  "fmt",
  "env-filter",
  "time",
] }
fastrace = { workspace = true, features = ["enable"] }
