[package]
name = "conductor"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "conductor"
path = "src/main.rs"

[lib]
name = "conductor"
path = "src/lib.rs"

[dependencies]
conductor_config = { path = "../../libs/config" }
conductor_engine = { path = "../../libs/engine" }
conductor_common = { path = "../../libs/common" }
conductor_tracing = { path = "../../libs/tracing" }
anyhow = { workspace = true }
actix-web = "4.4.1"
tracing-actix-web = "0.7.9"
tracing = { workspace = true }
openssl = { version = "0.10", features = ["vendored"] }
tracing-subscriber = { workspace = true, features = [
  "registry",
  "fmt",
  "env-filter",
  "time",
] }
minitrace = { version = "0.6", features = ["enable"] }
