[package]
name = "conductor"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "conductor"
path = "src/main.rs"

[lib]
name = "conductor"
path = "src/lib.rs"

[dependencies]
conductor_config = { path = "../../libs/config" }
conductor_engine = { path = "../../libs/engine" }
conductor_common = { path = "../../libs/common" }
actix-web = "4.4.1"
tracing = { workspace = true }
openssl = { version = "0.10", features = ["vendored"] }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }
